# TCL File Generated by Component Editor 18.1
# Sat May 04 17:07:27 JST 2019
# DO NOT MODIFY


# 
# MySendToFX2LP "MySendToFX2LP" v1.0
#  2019.05.04.17:07:27
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module MySendToFX2LP
# 
set_module_property DESCRIPTION ""
set_module_property NAME MySendToFX2LP
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME MySendToFX2LP
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL MySendToFX2LP
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file MySendToFX2LP.v VERILOG PATH MySendToFX2LP.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset reset Input 1


# 
# connection point in0
# 
add_interface in0 avalon_streaming end
set_interface_property in0 associatedClock clock
set_interface_property in0 associatedReset reset
set_interface_property in0 dataBitsPerSymbol 32
set_interface_property in0 errorDescriptor ""
set_interface_property in0 firstSymbolInHighOrderBits true
set_interface_property in0 maxChannel 0
set_interface_property in0 readyLatency 0
set_interface_property in0 ENABLED true
set_interface_property in0 EXPORT_OF ""
set_interface_property in0 PORT_NAME_MAP ""
set_interface_property in0 CMSIS_SVD_VARIABLES ""
set_interface_property in0 SVD_ADDRESS_GROUP ""

add_interface_port in0 asi_in0_data data Input 32
add_interface_port in0 asi_in0_valid valid Input 1
add_interface_port in0 asi_in0_ready ready Output 1


# 
# connection point fx2lp
# 
add_interface fx2lp conduit end
set_interface_property fx2lp associatedClock clock
set_interface_property fx2lp associatedReset ""
set_interface_property fx2lp ENABLED true
set_interface_property fx2lp EXPORT_OF ""
set_interface_property fx2lp PORT_NAME_MAP ""
set_interface_property fx2lp CMSIS_SVD_VARIABLES ""
set_interface_property fx2lp SVD_ADDRESS_GROUP ""

add_interface_port fx2lp coe_fx2lp_fd fd Output 8
add_interface_port fx2lp coe_fx2lp_slrd_n slrd_n Output 1
add_interface_port fx2lp coe_fx2lp_slwr_n slwr_n Output 1
add_interface_port fx2lp coe_fx2lp_sloe_n sloe_n Output 1
add_interface_port fx2lp coe_fx2lp_fifoadr fifoadr Output 2
add_interface_port fx2lp coe_fx2lp_pktend_n pktend_n Output 1
add_interface_port fx2lp coe_fx2lp_flag_n flag_n Input 3

