	QsysCore u0 (
		.clk_clk                                                                                         (<connected-to-clk_clk>),                                                                                         //                                             clk.clk
		.clk_0_clk                                                                                       (<connected-to-clk_0_clk>),                                                                                       //                                           clk_0.clk
		.dc_fifo_0_in_data                                                                               (<connected-to-dc_fifo_0_in_data>),                                                                               //                                    dc_fifo_0_in.data
		.dc_fifo_0_in_valid                                                                              (<connected-to-dc_fifo_0_in_valid>),                                                                              //                                                .valid
		.dc_fifo_0_in_ready                                                                              (<connected-to-dc_fifo_0_in_ready>),                                                                              //                                                .ready
		.mysendtofx2lp_0_fx2lp_fd                                                                        (<connected-to-mysendtofx2lp_0_fx2lp_fd>),                                                                        //                           mysendtofx2lp_0_fx2lp.fd
		.mysendtofx2lp_0_fx2lp_slrd_n                                                                    (<connected-to-mysendtofx2lp_0_fx2lp_slrd_n>),                                                                    //                                                .slrd_n
		.mysendtofx2lp_0_fx2lp_slwr_n                                                                    (<connected-to-mysendtofx2lp_0_fx2lp_slwr_n>),                                                                    //                                                .slwr_n
		.mysendtofx2lp_0_fx2lp_sloe_n                                                                    (<connected-to-mysendtofx2lp_0_fx2lp_sloe_n>),                                                                    //                                                .sloe_n
		.mysendtofx2lp_0_fx2lp_fifoadr                                                                   (<connected-to-mysendtofx2lp_0_fx2lp_fifoadr>),                                                                   //                                                .fifoadr
		.mysendtofx2lp_0_fx2lp_pktend_n                                                                  (<connected-to-mysendtofx2lp_0_fx2lp_pktend_n>),                                                                  //                                                .pktend_n
		.mysendtofx2lp_0_fx2lp_flag_n                                                                    (<connected-to-mysendtofx2lp_0_fx2lp_flag_n>),                                                                    //                                                .flag_n
		.pio_0_external_connection_export                                                                (<connected-to-pio_0_external_connection_export>),                                                                //                       pio_0_external_connection.export
		.pio_1_external_connection_export                                                                (<connected-to-pio_1_external_connection_export>),                                                                //                       pio_1_external_connection.export
		.reset_reset_n                                                                                   (<connected-to-reset_reset_n>),                                                                                   //                                           reset.reset_n
		.reset_0_reset_n                                                                                 (<connected-to-reset_0_reset_n>),                                                                                 //                                         reset_0.reset_n
		.spi_slave_to_avalon_mm_master_bridge_0_export_0_mosi_to_the_spislave_inst_for_spichain          (<connected-to-spi_slave_to_avalon_mm_master_bridge_0_export_0_mosi_to_the_spislave_inst_for_spichain>),          // spi_slave_to_avalon_mm_master_bridge_0_export_0.mosi_to_the_spislave_inst_for_spichain
		.spi_slave_to_avalon_mm_master_bridge_0_export_0_nss_to_the_spislave_inst_for_spichain           (<connected-to-spi_slave_to_avalon_mm_master_bridge_0_export_0_nss_to_the_spislave_inst_for_spichain>),           //                                                .nss_to_the_spislave_inst_for_spichain
		.spi_slave_to_avalon_mm_master_bridge_0_export_0_miso_to_and_from_the_spislave_inst_for_spichain (<connected-to-spi_slave_to_avalon_mm_master_bridge_0_export_0_miso_to_and_from_the_spislave_inst_for_spichain>), //                                                .miso_to_and_from_the_spislave_inst_for_spichain
		.spi_slave_to_avalon_mm_master_bridge_0_export_0_sclk_to_the_spislave_inst_for_spichain          (<connected-to-spi_slave_to_avalon_mm_master_bridge_0_export_0_sclk_to_the_spislave_inst_for_spichain>)           //                                                .sclk_to_the_spislave_inst_for_spichain
	);

